label: "JIRA"
url: "https://fernandotest.atlassian.net/browse/$issuePrefix"
message: "$issuePrefix"
color: "0055CC"
when: "$issuePrefix" 
invalidPRTitleComment: >
  ### Example  
  - ✅ &nbsp;[JIRA-1234] 기존 기능에 대한 개선 사항 반영  
  - ⚠️ &nbsp;기능에 대한 개선사항 반영  
  - ⛔️ &nbsp;Feature/hotissue  
  
  PR제목에는 반드시 `JIRA 이슈 티켓`이 포함이 되어있어야 합니다.   
  올바른 PR 제목 관리는 히스토리 관리에 도움이 되기 때문입니다. 😁  
  자세한 가이드는 [문서](http://www.naver.com)를 통해 확인 해보실 수 있습니다.   
